server:
  port: 9001
spring:  application:    name: ribbon-consumer
eureka:
  instance:    hostname: localhost
  client:
    healthcheck:      enabled: true
    service-url:      defaultZone: http://${eureka.instance.hostname}:8761/eureka/