server:
  port: 8771
spring:  application:    name: springboot-Client
  boot:    admin:      client:        url: http://localhost:8770
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS